sudo: required
services:
  - docker
language: bash
script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build image
  - docker build -t voldedore/rpi-kodi .
  # test image
  #- docker run voldedore/rpi-omv omv-sysinfo  | grep -A 3 -B 1 "openmediavault information"
  # push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
      TAG=$(grep "ENV VERSION" Dockerfile | awk 'NF>1{print $NF}')
      docker tag voldedore/rpi-kodi voldedore/rpi-kodi:$TAG
      docker push voldedore/rpi-kodi:$TAG
      docker push voldedore/rpi-kodi
    fi
